Controllers/CatalogoController.cs
using MiPrimerAppMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPrimerAppMVC.Controllers
{
    public class CatalogoController : Controller
    {
        // GET: Catalogo
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult listarProducto()
        {
            using (var db = new EJEMPLOMVCEntities())
            {
                var lst = (from producto in db.Producto
                           join categoria in db.Categoria
                           on producto.IDCATEGORIA equals categoria.IDCATEGORIA
                           select new LstProducto
                           {
                               IDPRODUCTO = producto.IDPRODUCTO,
                               DESCRIPCION = producto.DESCRIPCION,
                               PRECIO = producto.PRECIO,
                               IMAGEN = producto.IMAGEN,
                               NOMBRECATEGORIA = categoria.NOMBRE
                           }).ToList();
                var json = Json(lst, JsonRequestBehavior.AllowGet);
                json.MaxJsonLength = int.MaxValue;
                return json;
            }
        }
    }
    public class LstProducto 
    {
        public int IDPRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public string IMAGEN { get; set; }
        public int IDCATEGORIA { get; set; }
        public string NOMBRECATEGORIA { get; set; }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Categoria", "Index", "Categoria", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Producto", "Index", "producto", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Vista del cliente", "Index", "Catalogo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
   
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Content/bootstrap.min.js"></script>
</body>
</html>